
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01URXhNakEwTURZME1Wb1hEVE13TVRFeE1EQTBNRFkwTVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkVyCllBaUhuUkFJaHpBZ2pMQjY1UURTaE4vRis3bmxwTlpmZjhSYnNndFFzYWZxTEpXQWRQTm5LL1NoWGNKTXRFNVQKK1AxMXp4L3RhOHVYWndUYU02L3hEZlRtU0gzNjVzUUN0eHNMaHQ5OTFmdzlMVmwyZm9KU2JnY1Z0Q3NJOGlRawpodEJpVTZyOHd5UVNyTWI5a2RCTDAxMmUwNkloMENnRkNsalJJN3pSZzQxcis4VFkwZzE5cVJhQXdRaTJ5SjR0ClB1WkhGcTdITzltNHo1amtEZVVVU24vcnpvckI4RGxMMlZYWGQyMEdQaElnY3lxcDFEZE1icWk4a2hIVEV6SEsKUEZkK2RkaEdjTi9sdDVDQmQ3Q2xuNU55MndFaUZaMlNuU0JTZFhOT2VRTkhpMCtSWTJLTUdaVFhyZ0FTbjAxbQpUNWJtSnhLVUJ0ZmxNVm5VTGg4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLcVQyT0NqNmJacVhpME04bkpLeDFocHFacjYKZ2xoNk1xb1ZMcnhJbEFtTS9rMytUZ2xNSUwwTGFwSnkycjh4VGNxQm1WbEVydEdGTTRhTVhGbko0Mm93R1gyYwp5ejBoaStxd2NVR1NTclJYVUV2SE5kRjJDSDc1SXRFem00eEF5djZTR21RcmdodExVVjEzQkdiS2RJU2xCMnhsClVOdVVROE54bXgyUFVjeWRBMksyK2Z3UVJUTmdCZCtlanFNZkk1ZGRyQmVxdUZZSm1QTGsxVlExbXNQREk1MngKdXdWVnpaMEVySEVodVRmMThLQXdSanBCZWZLMXNGZXlvakdpQVgyczF0b3BhM293QUdwZFFzT0pTRU9aek0zagpsbnA1cGNIUHorZ0Z5Z2hBdkJ6bEg2OVh2WWlFOWVIQTkyYTFkUXVqK3FFNVNnRiszU1RrQTI5YVNjVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://89470acf-e875-4c99-b12f-b52c13bc18a5.ap-south-1.linodelke.net:443
  name: lke13154

users:
- name: lke13154-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ildhb25CV2l5eWdRY0ZKYVhWM3lfemVFTmVhYTBYT1VIQkNaTzd4bmpWNncifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4td2xybGIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTJhNmY2ZWItNWY3MS00YjNlLWI3YzktOWU0MWM0OTk4NzRmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.f8nMl4SKYhYOq2gHFTKIHwNysGMahk5VKzw4jCCcj-bOvVc-qzRk8LPdS8Tt0Mefmh2Tlh4wnBg2UrZh2pBfOcVaPcTC2J6_KYeRpiXHAh-02skadOjMh2ARU-iJkvhf6wE95J_fFoESP5UtZaRwmqiq17vuH8zX9yaoPwWgyAUY4ITGBY2xxQxZ9N5xZkd67x1Ssg2v_5LoON2Gww6TCIR3VeZU8Am4yEQyAv4OSYwSwr8jJm0_x1ZZ-L4R3gKP0rnIfOc7G5YPEs4FeJSB9PxpPVIodpgc2-9gQp8l0hrTJIsnrBMqnD37gWTLpKFjpdZUUuQnSQrCgSmR8l6gdw

contexts:
- context:
    cluster: lke13154
    namespace: default
    user: lke13154-admin
  name: lke13154-ctx

current-context: lke13154-ctx
