global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  scrape_timeout: 15s # Timeout after 15 seconds

scrape_configs:
  - job_name: "job-name"
    scrape_interval: 10s # Override the default global interval for this job
    scrape_timeout: 10s # Override the default global timeout for this job
    metrics_path: '/actuator/prometheus'
    static_configs:
    # First group of scrape targets
    - targets: ['br1:8081', 'br2:8082']
      labels:
        group: 'first-group'

    # Second group of scrape targets
    - targets: ['br1:8081', 'br2:8082']
      labels:
        group: 'second-group'